<?php
/**
 * Created by PhpStorm.
 * User: longbob
 * Date: 2018/12/24
 * Time: 10:49 PM
 */

namespace EasySwoole\WeChat\Test\Cases\Utility;

use EasySwoole\WeChat\Utility\HttpClient;
use PHPUnit\Framework\TestCase;

class HttpClientTest extends TestCase
{

    /**
     * @var HttpClient
     */
    private $cli;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->cli = new HttpClient();
    }

    public function testGetHttp()
    {
        $data = $this->cli->get('http://www.kuaidi100.com/query?type=youzhengguonei&postid=9894333501509&id=1&valicode=&temp=0.9686391934062681');
        echo $data;
        $this->assertNotEmpty($data);
    }

//    public function testGetHttps()
//    {
//        go(function(){
//            $data = $this->cli->get('https://www.baidu.com');
//            $this->assertNotEmpty($data);
//        });
//
//    }

    public function testPostHttp()
    {
        $data = $this->cli->post('http://www.baidu.com', [
            'key' => '美女'
        ]);
        $this->assertNotEmpty($data);
    }

//    public function testPostHttps()
//    {
//        go(function(){
//            $data = $this->cli->post('https://www.baidu.com', [
//                'key' => '美女'
//            ]);
//            $this->assertNotEmpty($data);
//        });
//    }

    public function testPostXml()
    {
        $data = $this->cli->postXML('http://www.baidu.com', '<?xml?>');
        $this->assertNotEmpty($data);
    }

    public function testPostJson()
    {
        $data = $this->cli->postJSON('http://www.baidu.com', '{"key" : "test"}');
        $this->assertNotEmpty($data);
    }
}